name: Osmo
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.2"
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: C5G4T4U48J
    CODE_SIGN_STYLE: Automatic

targets:
  Osmo:
    type: application
    platform: iOS
    sources:
      # Root
      - path: OsmoApp.swift
      - path: ContentView.swift
      - path: Shaders.metal
      - path: Assets.xcassets
      # Models
      - path: Models/APIModels.swift
        group: Models
      - path: Models/Message.swift
        group: Models
      # Views
      - path: Views/ChatSheetView.swift
        group: Views
      - path: Views/ConfirmationBannerView.swift
        group: Views
      - path: Views/CosmicBackground.swift
        group: Views
      - path: Views/HistorySheetView.swift
        group: Views
      - path: Views/HomeView.swift
        group: Views
      - path: Views/ControlCenterView.swift
        group: Views
      - path: Views/AttachmentView.swift
        group: Views
      # ViewModels
      - path: ViewModels/AppViewModel.swift
        group: ViewModels
      # Utilities
      - path: Utilities/GlassEffect+Adaptive.swift
        group: Utilities
      # ParticleOrb
      - path: ParticleOrb/ParticleOrbView.swift
        group: ParticleOrb
      - path: ParticleOrb/ParticleShape.swift
        group: ParticleOrb
      - path: ParticleOrb/ParticleSystem.swift
        group: ParticleOrb
      - path: ParticleOrb/ParticleStateMachine.swift
        group: ParticleOrb
      - path: ParticleOrb/MotionControllers.swift
        group: ParticleOrb
      - path: ParticleOrb/MorphController.swift
        group: ParticleOrb
      - path: ParticleOrb/ShapeLibrary.swift
        group: ParticleOrb
      # Services
      - path: Services/APIClient.swift
        group: Services
      - path: Services/APIConfig.swift
        group: Services
      - path: Services/AuthManager.swift
        group: Services
      - path: Services/EventKitManager.swift
        group: Services
      - path: Services/KeychainHelper.swift
        group: Services
      - path: Services/SpeechRecognizer.swift
        group: Services
      - path: Services/ReminderManager.swift
        group: Services
      - path: Services/NotificationManager.swift
        group: Services
      - path: Services/DeviceControlManager.swift
        group: Services
      - path: Services/CameraManager.swift
        group: Services
      - path: Services/MessageManager.swift
        group: Services
      - path: Services/MusicManager.swift
        group: Services
      - path: Services/MediaManager.swift
        group: Services
      - path: Services/OnboardingManager.swift
        group: Services
      - path: Services/LocationManager.swift
        group: Services
      - path: Services/AppLauncherManager.swift
        group: Services
      - path: Services/TranslationManager.swift
        group: Services
      - path: Services/NavigationManager.swift
        group: Services
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.Osmo
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_APPROACHABLE_CONCURRENCY: YES
        SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
        SWIFT_EMIT_LOC_STRINGS: YES
        TARGETED_DEVICE_FAMILY: "1,2"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "1.0.0"
        INFOPLIST_KEY_CFBundleDisplayName: Osmo
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        INFOPLIST_KEY_NSAppTransportSecurity_NSAllowsArbitraryLoads: NO
        INFOPLIST_KEY_NSCalendarsUsageDescription: "Osmo needs calendar access to manage your events locally."
        INFOPLIST_KEY_NSCalendarsFullAccessUsageDescription: "Osmo needs full calendar access to create, update, and delete events on your behalf."
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "Speech recognition is used to transcribe your voice commands."
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Microphone access is needed to record your voice for speech-to-text."
        INFOPLIST_KEY_NSRemindersFullAccessUsageDescription: "Osmo needs reminders access to create, complete, and manage your reminders."
        INFOPLIST_KEY_NSCameraUsageDescription: "Osmo uses the camera to take photos and record video on your behalf."
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "Osmo saves captured photos and videos to your photo library."
        INFOPLIST_KEY_NSAppleMusicUsageDescription: "Osmo controls music playback through Apple Music."
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Osmo uses your location for navigation, local search, and commute estimates."
